stormpath/stormpath-sdk-ruby

.travis.yml
README.md
lib/stormpath-sdk/resource/application.rb
spec/resource/application_spec.rb

PR covering task https://github.com/stormpath/stormpath-sdk-ruby/issues/92

Id site multitenancy

---

.travis.yml
README.md
spec/resource/directory_spec.rb

PR for task https://github.com/stormpath/stormpath-sdk-ruby/issues/79

Password import mcf

---

stormpath-sdk.gemspec

Format from https://spdx.org/licenses/ per rubygems spec
Closes #49

License added to gemspec; is Apache-2.0

---

README.md

As asked by @rdegges in #110 . I didn't add updating and deleting on purpose since it's the same as for all the other resources.
If you think it's necessary, I'll update the PR.
Please review, thnx.

Add Organization docs to README

---

README.md
lib/stormpath-sdk/auth/basic_login_attempt.rb
lib/stormpath-sdk/data_store.rb
spec/resource/application_spec.rb

@omgitstom submitted the issue #107 . Before I could document it, I had to enable the feature in the Ruby SDK.
@ecrisostomo please review.

Login attempt with organization namekey

---

lib/stormpath-sdk/auth/username_password_request.rb
lib/stormpath-sdk/data_store.rb
lib/stormpath-sdk/resource/application.rb
spec/resource/application_spec.rb

Support for specifying the account store when reseting passwords. Works both with an href and a nameKey.

Reset password account store

---

lib/stormpath-sdk/client.rb
spec/client_spec.rb
spec/spec_helper.rb

Add delegate to organizations and write specs for search functionality

---

lib/stormpath-sdk/resource/account.rb
lib/stormpath-sdk/resource/application.rb
lib/stormpath-sdk/resource/custom_data.rb
lib/stormpath-sdk/resource/directory.rb
lib/stormpath-sdk/resource/group.rb
lib/stormpath-sdk/resource/organization.rb
lib/stormpath-sdk/resource/tenant.rb
spec/resource/account_spec.rb
spec/resource/application_spec.rb
spec/resource/directory_spec.rb
spec/resource/group_spec.rb
spec/resource/organization_spec.rb
spec/resource/tenant_spec.rb
spec/support/custom_data_storage_behavior.rb

Add timestamp getters

---

lib/stormpath-sdk.rb
lib/stormpath-sdk/resource/account_creation_policy.rb
lib/stormpath-sdk/resource/directory.rb
spec/resource/account_creation_policy_spec.rb

Hey @ecrisostomo, please check this out.

Add AccountCreationPolicy Resource

---

spec/resource/directory_spec.rb

this adds a test for importing BCrypt 2A hashes

adding test for importing BCrypt 2A hashes

---

lib/stormpath-sdk/error.rb
lib/stormpath-sdk/oauth/error.rb
lib/stormpath-sdk/resource/error.rb
spec/resource/application_spec.rb

Pull request for issue https://github.com/stormpath/stormpath-sdk-ruby/issues/126

Add request id to error resource

---

README.md

adding documentation on how to use enterprise product

---

lib/stormpath-sdk.rb
lib/stormpath-sdk/data_store.rb
lib/stormpath-sdk/http/http_client_request_executor.rb
lib/stormpath-sdk/oauth/authenticator.rb
lib/stormpath-sdk/oauth/social_grant.rb
lib/stormpath-sdk/oauth/social_grant_request.rb
lib/stormpath-sdk/provider/google/google_provider_data.rb
spec/resource/application_spec.rb
spec/spec_helper.rb
spec/support/mocked_provider_accounts.rb

Pull request for issue https://github.com/stormpath/stormpath-sdk-ruby/issues/139

Create stormpath_social grant type

---

README.md
lib/stormpath-sdk/oauth/stormpath_grant_request.rb
spec/resource/application_spec.rb

PR resolves issue: https://github.com/stormpath/stormpath-sdk-ruby/issues/136

Add option to exchange stormpath_token for an access_token with the registered status

---

README.md
lib/stormpath-sdk/http/http_client_request_executor.rb
lib/stormpath-sdk/oauth/password_grant.rb
lib/stormpath-sdk/oauth/password_grant_request.rb
spec/resource/application_spec.rb

PR resolves issue: https://github.com/stormpath/stormpath-sdk-ruby/issues/135

Support organizationNameKey for oauth token exchange

---

spec/oauth/access_token_authentication_result_spec.rb
spec/support/resource_matchers.rb

PR for issue: https://github.com/stormpath/stormpath-sdk-ruby/issues/128
Please review. Not sure if anything else needed here.

Add specs that check for stt header in jwt

---

lib/stormpath-sdk/resource/directory.rb
spec/resource/directory_spec.rb

PR for issue https://github.com/stormpath/stormpath-sdk-ruby/issues/155
Now you can:
```ruby
directory.organizations
```
and
```ruby
directory.organizations.get(organization.href)
```
@DamirSvrtan please review and merge if all is ok.

Add organizations endpoint on directory

---

README.md
lib/stormpath-sdk.rb
lib/stormpath-sdk/resource/application.rb
lib/stormpath-sdk/util/uri_builder.rb
spec/util/uri_builder_spec.rb

PR for issue https://github.com/stormpath/stormpath-sdk-ruby/issues/47

Fix bug when loading application that has a forward slash in client_credentials

---

lib/stormpath-sdk/resource/organization.rb
spec/resource/organization_spec.rb

Implements solution for issue: https://github.com/stormpath/stormpath-sdk-ruby/issues/167

Add create method on organizations accounts collection

---

lib/stormpath-sdk/http/utils.rb
spec/resource/application_spec.rb

PR for issue https://github.com/stormpath/stormpath-sdk-ruby/issues/154

Decode encoded periods in http utils

---

.travis.yml
lib/stormpath-sdk.rb
lib/stormpath-sdk/cache/memcached_store.rb
spec/data_store_spec.rb
spec/spec_helper.rb
stormpath-sdk.gemspec

Resolves issue https://github.com/stormpath/stormpath-sdk-ruby/issues/168

Add memcached store as option for the ruby sdk cache store

---

lib/stormpath-sdk.rb
lib/stormpath-sdk/auth/http_basic_authentication.rb
lib/stormpath-sdk/auth/http_bearer_authentication.rb
lib/stormpath-sdk/oauth/local_access_token_verification.rb
lib/stormpath-sdk/oauth/remote_access_token_verification.rb
lib/stormpath-sdk/oauth/verify_access_token.rb
lib/stormpath-sdk/oauth/verify_token_result.rb
spec/auth/http_basic_authentication_spec.rb
spec/auth/http_bearer_authentication_spec.rb
spec/resource/application_spec.rb

Pull request for issue https://github.com/stormpath/stormpath-sdk-ruby/issues/165
Please review @DamirSvrtan and don't merge into master until your merge https://github.com/stormpath/stormpath-sdk-ruby/pull/176 into this branch.

Implement option to verify access_token locally

---

.travis.yml
lib/stormpath-sdk/cache/memcached_store.rb
lib/stormpath-sdk/data_store.rb
spec/data_store_spec.rb

PR for issue https://github.com/stormpath/stormpath-sdk-ruby/issues/34

Pass store_opts hash when instantiating the data store caching system

---

lib/stormpath-sdk.rb
lib/stormpath-sdk/client.rb
lib/stormpath-sdk/resource/account.rb
lib/stormpath-sdk/resource/account_link.rb
lib/stormpath-sdk/resource/linked_account.rb
spec/client_spec.rb
spec/resource/account_link_spec.rb
spec/resource/account_spec.rb
spec/resource/linked_account_spec.rb

PR for issue https://github.com/stormpath/stormpath-sdk-ruby/issues/179

Implement manual account linking functionality

---

lib/stormpath-sdk/oauth/error.rb
lib/stormpath-sdk/oauth/local_access_token_verification.rb
lib/stormpath-sdk/oauth/remote_access_token_verification.rb

PR for https://github.com/stormpath/stormpath-sdk-ruby/issues/184

Add oauth jwt errors

---

lib/stormpath-sdk.rb
lib/stormpath-sdk/provider/twitter/twitter_provider.rb
lib/stormpath-sdk/provider/twitter/twitter_provider_data.rb
spec/provider/provider_spec.rb
spec/support/mocked_provider_accounts.rb

Solves https://github.com/stormpath/stormpath-sdk-ruby/issues/190

Create twitter provider and add specs

---

lib/stormpath-sdk/provider/account_request.rb
lib/stormpath-sdk/provider/account_resolver.rb
lib/stormpath-sdk/resource/application.rb
spec/provider/account_resolver_spec.rb

Resolves https://github.com/stormpath/stormpath-sdk-ruby/issues/197

Optional account store during account resolution for provider directories

---

lib/stormpath-sdk.rb
lib/stormpath-sdk/resource/account_linking_policy.rb
lib/stormpath-sdk/resource/application.rb
lib/stormpath-sdk/resource/organization.rb
spec/resource/account_linking_policy_spec.rb
spec/resource/application_spec.rb
spec/resource/organization_spec.rb

Resolves https://github.com/stormpath/stormpath-sdk-ruby/issues/180

Automatic account linking

---

spec/resource/collection_spec.rb
spec/resource/directory_spec.rb
spec/spec_helper.rb
spec/support/custom_data_save_period.rb

Solves https://github.com/stormpath/stormpath-sdk-ruby/issues/200

Add spec for testing directory custom data search

---

lib/stormpath-sdk/resource/application.rb
spec/resource/application_spec.rb

Resolves https://github.com/stormpath/stormpath-sdk-ruby/issues/207

Add require_mfa option to jwt payload

---

lib/stormpath-sdk/auth/register_service_provider.rb
lib/stormpath-sdk/resource/application.rb
lib/stormpath-sdk/resource/saml_identity_provider.rb
spec/auth/register_service_provider_spec.rb
spec/resource/application_spec.rb
spec/resource/registered_saml_service_provider_spec.rb
spec/resource/saml_identity_provider_spec.rb
spec/resource/saml_service_provider_registration_spec.rb

These are the implemented changes from PR: https://github.com/stormpath/stormpath-sdk-ruby/pull/205

Refactor RegisterServiceProvider interface

---

README.md
lib/stormpath-sdk.rb
lib/stormpath-sdk/data_store.rb
lib/stormpath-sdk/provider/ldap/ldap_provider.rb
lib/stormpath-sdk/resource/agent.rb
spec/provider/provider_spec.rb
spec/resource/agent_spec.rb
spec/resource/directory_spec.rb
spec/resource/saml_identity_provider_spec.rb
spec/support/resource_helpers.rb

Resolves https://github.com/stormpath/stormpath-sdk-ruby/issues/161

Implement CRUD functionality for LDAP directories
